### ISSUE TITLE
1.0.4 ignores existing palettes

### ISSUE THREAD

**Issue by vdh** [callaa/Drawpile#358] opened 2016-08-27 08:18 UTC
Tried to use my existing palettes, which are still there in `~/Library/Application Support/drawpile/palettes/*.gpl`, but the app just ignores them and instead just shows a bunch of locked palettes about Ponies and such 😦

**Comment by callaa** [comment] 2016-08-27 08:29
Confirmed. This is a regression that affects the OSX version only.

**Comment by callaa** [comment] 2016-08-27 08:44
This is now fixed. Since it's a fairly serious bug, I made an updated build of 1.0.4: https://drawpile.net/files/osx/Drawpile%201.0.4-1.dmg

**Closed by callaa** 2016-08-27 08:44 UTC
Labels: Bug
