### ISSUE TITLE
Mystery crash

### ISSUE THREAD

**Issue by pachuco** [callaa/Drawpile#232] opened 2015-08-09 13:59 UTC
I updated to the freshly released 1.0.1 and managed to send Drawpile crashing in flames on first run and have it repeatable.
The crash occurs both online and offline(dprec playback).
Attached are dumps and logs of 4 crashes: http://a.pomf.cat/zulahe.zip
Last crash is with dprec playback.

Steps to reproduce:
1. Joining a specific drawpile session with long backlog(takes about 5 minutes to reach completion and half an hour for dprec)
2. Wait for session to finish.
3. Click on canvas(I had eraser selected; I am able to chat freely until crash).
4. CRASH AND BURN

As for posting the dprec, I'll have to get permission for that.

**Comment by callaa** [comment] 2015-08-09 14:58
Based on the dump, the crash appears to be caused by a divide-by-zero error. I don't know how to interpret windows crash dumps any further, so I'm not yet sure where exactly it happens. If you can send me the recording (e.g. directly by email, no need to put it anywhere public) I can try running it in a debugger myself to see where it crashes.

**Comment by callaa** [comment] 2015-08-09 15:15
Here's an updated version of the main executable: http://drawpile.net/files/win/drawpile-1.0.1.1.zip

Can you try if it fixes the bug?

**Comment by pachuco** [comment] 2015-08-09 15:28
I'm gonna have to request something here. Can I have option in dprec player to play 'as fast as possible'(like when joining a server) so it doesn't take half a bloody hour for whole session to play back?

**Comment by callaa** [comment] 2015-08-09 15:34
If you turn the speed dial to maximum and set max pauses to zero, that's about as fast as it goes. Although, since the crash happens in the input handling part of the program, I would guess that you don't need to play back the entire recording to trigger the bug.

**Comment by pachuco** [comment] 2015-08-09 15:35
So how much do I need to play?

**Comment by pachuco** [comment] 2015-08-09 15:37
Nevermind, I don't need to play anything.
Hahahahahahahahahaha.

**Comment by pachuco** [comment] 2015-08-09 15:39
Yeah, no more crash on canvas click.
I'm half-tempted to run it through the dprec playback just to be sure.

**Comment by callaa** [comment] 2015-08-09 16:01
Ok, great! I'll update the release packages.
I managed to replicate the bug myself now too. The exact steps are:

1. Start drawpile with stroke smoother disabled
2. Click or draw anywhere on the canvas

This triggers a division by zero error, because there is no smoothing data and that fact was not checked in the pen-up event handler before trying to get smoothed points.

**Closed by callaa** 2015-08-09 16:01 UTC
Labels: Bug
