### ISSUE TITLE
Does not build with the latest libupnp

### ISSUE THREAD

**Issue by irah-000** [callaa/Drawpile#277] opened 2015-10-01 14:12 UTC
I get:

```
Drawpile/src/client/net/upnp.cpp:95:64: error: invalid conversion from ‘int*’ to ‘unsigned char’ [-fpermissive]
  d->devices = upnpDiscover(2000, nullptr, nullptr, 0, 0, &error);
                                                                ^
Drawpile/src/client/net/upnp.cpp:95:64: error: too few arguments to function ‘UPNPDev* upnpDiscover(int, const char*, const char*, int, int, unsigned char, int*)’
```
Perhaps add the missing parameter? (ttl?)
```c
d->devices = upnpDiscover(2000, nullptr, nullptr, 0, 0, SOMETHING_HERE, &error);
```

**Comment by callaa** [comment] 2015-10-01 16:40
Duplicate of issue #273. Try the latest stable branch version.

**Closed by callaa** 2015-10-01 16:40 UTC
