### ISSUE TITLE
Random crash while dragging layer in an online session with 1 partner, data not saved

### ISSUE THREAD

**Issue by chetchaka** [callaa/Drawpile#166] opened 2015-01-06 02:06 UTC
While drawing using 6-9 layers in drawpile, we were able to move layers successfully. After some nonspecific layer deletion via Ctrl + Z, I moved a layer, which might have caused the crash. Data was completely unable to be saved, and crashed for my drawing partner as well with the exact same error "This program has stopped working". The internet was fully operational the entire time.
The crash could also have been caused by moving a layer as it was being modified or drawn on, but I haven't tested either possibility.

I wasn't smart and didn't record whatever Windows put on the screen at that moment. I didn't get any error codes, and Drawpile doesn't seem to have a logging function for errors of any kind, nor any way to create / restore emergency backup files.

CPU: AMD Athlon II X4 630, 2800 Mhz, 4 cores
GPU: ATI Radeon HD 4800 Series
RAM: 4 GB
OS: Windows 7 64x Home Premium SP1 build 7601
Drawpile Version: 0.9.6

EDIT: Got all the errors from the event viewer in Windows!

1/5/2015 7:43:42 PM
Faulting application name: drawpile.exe, version: 0.9.6.0, time stamp: 0x004ead50
Faulting module name: drawpile.exe, version: 0.9.6.0, time stamp: 0x004ead50
Exception code: 0xc0000005
Fault offset: 0x00076213
Faulting process id: 0xbe8
Faulting application start time: 0x01d0293d3f964d2a
Faulting application path: C:\Program Files (x86)\Drawpile\drawpile.exe
Faulting module path: C:\Program Files (x86)\Drawpile\drawpile.exe
Report Id: 71751ea7-9545-11e4-bb85-d48564ab6b81

- System 

     - Provider 
          [ Name]  Application Error 
     - EventID: 1000 
          [ Qualifiers]  0 
       Level: 2 
       Task: 100 
       Keywords: 0x80000000000000 
     - TimeCreated 
           [ SystemTime]  2015-01-06T01:43:42.000000000Z 
       EventRecordID: 3227 
       Channel: Application 

- EventData 

   drawpile.exe 
   0.9.6.0 
   004ead50 
   drawpile.exe 
   0.9.6.0 
   004ead50 
   c0000005 
   00076213 
   be8 
   01d0293d3f964d2a 
   C:\Program Files (x86)\Drawpile\drawpile.exe 
   C:\Program Files (x86)\Drawpile\drawpile.exe 
   71751ea7-9545-11e4-bb85-d48564ab6b81

**Comment by callaa** [comment] 2015-01-06 11:21
Thanks for the report! I managed to reproduce the bug (the reordered layer list somehow goes out of sync with the actual layer list.) 
Since I've already found another nasty bug in the current version, I'll probably make the next release a bit sooner than I originally planned.

**Comment by callaa** [comment] 2015-01-06 13:59
This is now fixed. The problem was that the program didn't check if the new layer order was valid. It seems the bug is triggered when the creation of a layer is undone, but a layer reorder command referencing the deleted layer is not. This can happen in multiuser mode, but apparently also with just one user, although I haven't yet figured out how. Nevertheless, the updated code handles this special case gracefully without crashing.

**Closed by callaa** 2015-01-06 13:59 UTC
Labels: Bug
