### ISSUE TITLE
[Beta 2.0] Jagged lines 

### ISSUE THREAD

**Issue by coffeemugtime** [callaa/Drawpile#349] opened 2016-08-07 00:07 UTC
Hello. I use a Cintiq 22hd on Windows 10. When I launched Drawpile I get these jagged lines, even with smoothing turned all the way up.
![2016-08-06_16h59_29](https://cloud.githubusercontent.com/assets/16845492/17459697/1db5d39a-5bf8-11e6-9fe5-21ef5ac088a2.png)

I found out that lowering the smoothing and turning it back up fixes the problem.

**Comment by callaa** [comment] 2016-08-07 09:56
Thank you for the report! This was indeed a real regression and is now fixed. The problem was quite simple: the smoothing value was not initialized for new documents and thus defaulted to zero even when the slider was set to something else.

**Closed by callaa** 2016-08-07 09:56 UTC
