### ISSUE TITLE
Eraser Hard mode Issue

### ISSUE THREAD

**Issue by Sonruks** [callaa/Drawpile#351] opened 2016-08-07 21:46 UTC
If you set eraser hardness less than 100% (at 50% for example) and then choose Hard edge mode, then it will work like a binary brush (pen tool), like expected. But if you choose another tool and than choose eraser again (or just choose eraser 2nd time) it will be with soft edges, although mode switch will be still at Hard mode. Only if hardness was 100% before you choose Hard mode it works fine.

**Comment by callaa** [comment] 2016-08-09 14:35
Confirmed. This bug exists both in 1.0.4 and 2.0 beta. Thanks for reporting! I'll fix this in the beta branch and backport it to stable if I make another 1.0.x release.

**Comment by callaa** [comment] 2016-09-24 10:19
This bug is now fixed, both in the stable and beta branches. Since there is also one other important bug fix in the stable branch, I will release at least one more 1.0.x version before 2.0 final.

**Closed by callaa** 2016-09-24 10:19 UTC
Labels: Bug
